In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from backend.data_processing_service import DataProcessingService

# Initialize DataProcessingService
data_processor = DataProcessingService(seq_length=10, pred_window=1, batch_size=10)
data = np.loadtxt('data/normalized_apple_prices.csv')
# data = data_processor.get_sample_data(length=50)

# Normalize the data
data_normalized, scaler = data_processor.normalize_data(data)

# Create sequences
x_data, y_data = data_processor.create_sequences(data_normalized)

# Split data into training and test sets
x_train, x_test, y_train, y_test = data_processor.split_data(x_data, y_data, train_ratio=0.8)

# Convert data to PyTorch tensors
x_train = torch.tensor(x_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
x_test = torch.tensor(x_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)


In [2]:
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

torch.Size([102, 10, 1]) torch.Size([102, 1, 1]) torch.Size([26, 10, 1]) torch.Size([26, 1, 1])


In [3]:
from backend.model_service import ModelService

In [31]:
import torch
import torch.nn as nn

class TimeSeriesGenerator(ModelService):
    def __init__(self, input_dim, output_dim, hidden_dim):
        super(TimeSeriesGenerator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
            # nn.Tanh()
        )

    def forward(self, x):
        return self.model(x)
    
    @staticmethod
    def reshape_input(s):
        return s.permute(0, 2, 1)

class TimeSeriesDiscriminator(ModelService):
    def __init__(self, input_dim, hidden_dim):
        super(TimeSeriesDiscriminator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)
    
    @staticmethod
    def reshape_input(s):
        return s.permute(0, 2, 1)



In [32]:
class GAN(ModelService):
    def __init__(self, generator, discriminator, gen_input_dim, data_dim, lr=0.0002, betas=(0.5, 0.999)):
        super(GAN, self).__init__()
        self.generator = generator
        self.discriminator = discriminator
        self.gen_input_dim = gen_input_dim
        self.data_dim = data_dim
        
        self.criterion = nn.MSELoss()
        self.optimizer_g = torch.optim.Adam(self.generator.parameters(), lr=lr, betas=betas)
        self.optimizer_d = torch.optim.Adam(self.discriminator.parameters(), lr=lr, betas=betas)

    def train(self, x_train, y_train, epochs):
        for epoch in range(epochs):
            for i in range(len(x_train)):
                real_data = x_train[i]
                real_labels = y_train[i].unsqueeze(1)

                # Train Discriminator
                self.optimizer_d.zero_grad()
                
                # Real data
                real_output = self.discriminator(real_data.t())         # Extract reshaping too the Discrimiator class
                real_loss = self.criterion(real_output, real_labels.squeeze(0))
                
                # Fake data
                noise = torch.randn(1, self.gen_input_dim)
                fake_data = self.generator(noise)
                fake_labels = torch.zeros(1, 1)  # Fake labels are 0
                fake_output = self.discriminator(fake_data)
                fake_loss = self.criterion(fake_output, fake_labels)
                
                # Total discriminator loss
                d_loss = real_loss + fake_loss
                d_loss.backward()
                self.optimizer_d.step()
                
                # Train Generator
                self.optimizer_g.zero_grad()
                
                noise = torch.randn(1, self.gen_input_dim)
                fake_data = self.generator(noise)
                fake_output = self.discriminator(fake_data)
                g_loss = self.criterion(fake_output, real_labels)
                
                g_loss.backward()
                self.optimizer_g.step()
            
            print(f'Epoch [{epoch+1}/{epochs}]  Loss D: {d_loss.item()}, Loss G: {g_loss.item()}')


In [29]:
# Usage example:
# Define model parameters
gen_input_dim = 10
# data_dim = 30  # Length of the time series
input_size = data_processor.seq_length
hidden_dim = 64
# output_size = data_processor.pred_window

# Instantiate models
# generator = TimeSeriesGenerator(gen_input_dim, data_dim, hidden_dim)
generator = TimeSeriesGenerator(input_dim=gen_input_dim, output_dim=input_size, hidden_dim=hidden_dim)
# discriminator = TimeSeriesDiscriminator(data_dim, hidden_dim)
discriminator = TimeSeriesDiscriminator(input_dim=input_size, hidden_dim=hidden_dim)
gan = GAN(generator, discriminator, gen_input_dim, input_size)

# Train the GAN model
epochs = 10
gan.train(x_train, y_train, epochs)

d:\projects\times_fw\.venv\lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([1, 1, 1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Epoch [1/10]  Loss D: 0.5972247123718262, Loss G: 0.1938854455947876
Epoch [2/10]  Loss D: 0.388442724943161, Loss G: 0.06010378897190094
Epoch [3/10]  Loss D: 0.31770098209381104, Loss G: 0.01388280838727951
Epoch [4/10]  Loss D: 0.2915491759777069, Loss G: 0.008138542994856834
Epoch [5/10]  Loss D: 0.2804330587387085, Loss G: 0.008363691158592701
Epoch [6/10]  Loss D: 0.27364087104797363, Loss G: 0.007428688928484917
Epoch [7/10]  Loss D: 0.2699657678604126, Loss G: 0.0072815450839698315
Epoch [8/10]  Loss D: 0.26761341094970703, Loss G: 0.0073517244309186935
Epoch [9/10]  Loss D: 0.2665179371833801, Loss G: 0.007844784297049046
Epoch [10/10]  Loss D: 0.2646543085575104, Loss G: 0.007210987154394388


In [25]:
x_test[-3], y_test[-3]

(tensor([[-0.0986],
         [ 0.0676],
         [-0.0713],
         [-0.0696],
         [-0.0396],
         [-0.0436],
         [ 0.0216],
         [ 0.0265],
         [-0.0417],
         [-0.0789]]),
 tensor([[-0.0580]]))

In [26]:
# 2. Pass test data through discriminator (optional)
test_predictions = gan.discriminator(x_test[-3].t())

# 3. Evaluate generated data using discriminator (optional)
generated_predictions = gan.discriminator(x_test[-3].t())


In [30]:
test_predictions, generated_predictions

(tensor([[0.0991]], grad_fn=<SigmoidBackward0>),
 tensor([[0.0991]], grad_fn=<SigmoidBackward0>))

In [ ]:
# Initialize the model
input_size = data_processor.seq_length
output_size = data_processor.pred_window
model = LinRegNN(input_size, output_size)


# Define loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
x_train_rs,x_test_rs= model.reshape_input(x_train),model.reshape_input(x_test)
epochs = 10
model.train_loop(model, criterion, optimizer, x_train_rs, y_train, epochs, directory = "backend/checkpoints/lr01_")
# Eval
model.evaluation(model, x_test_rs, y_test, criterion)

Epoch [1/10], Loss: 0.1760
Epoch [2/10], Loss: 0.1008
Epoch [3/10], Loss: 0.0839
Epoch [4/10], Loss: 0.0741
Epoch [5/10], Loss: 0.0655
Checkpoint saved at epoch 5
Epoch [6/10], Loss: 0.0581
Epoch [7/10], Loss: 0.0518
Epoch [8/10], Loss: 0.0467
Epoch [9/10], Loss: 0.0425
Epoch [10/10], Loss: 0.0392
Checkpoint saved at epoch 10
Test Loss: 0.0181


0.018084477803628173

In [ ]:
model.register(model, name="template_test")

Entire model saved successfully.


In [ ]:
from backend.model_service import ModelService
model_service = ModelService()
loaded_model = model_service.load_registered_model("backend/models/template_test")

Entire model loaded successfully.
